### ISSUE TITLE
Handling http get/post (using axios) from front end (need to write inside of .js file) and back end. 

### ISSUE THREAD

**Issue by Kuzame** [ReflexCS180/ReflexManagment#41]
Been researching for 9h straight on Monday, but couldn't solve it for the time being. Need help on this until I can help back after Wed afternoon (cs141 midterm). Very helpful resources:
https://www.techiediaries.com/create-react-app-django/  (check axios section)
https://stackoverflow.com/questions/39298644/using-post-in-react-without-form
https://hackernoon.com/creating-websites-using-react-and-django-rest-framework-b14c066087c7
http://timonweb.com/posts/make-drf-and-axios-work-nicely-together/

**Comment by Kuzame** [comment]
example usage for using axios on frontend's my-app/src/Register.js (though I'm unsure if it has correct syntax or not)
![capture](https://user-images.githubusercontent.com/15834251/32490517-47dec7d4-c368-11e7-8b8c-a32ef818a193.PNG)

**Comment by jonei005** [comment]
For the 'localhost:3000' part, you would put the url of the API we are going to call. So somehow in the server we have to first set up an api to handle get and post requests, or else our calls from the frontend will do nothing. So assuming we have a Django API set up somewhere, it has to run at a different port than React. Then we can use that port to call the API.
