### ISSUE TITLE
Board to Dashboard Crash

### ISSUE THREAD

**Issue by RBoshae** [ReflexCS180/ReflexManagment#69]
**Issue** 
If a user logs in then clicks the 'Board' link through the nav bar and then clicks the 'dashboard' link, the page crashes. 

**Proposed Fix**
Hide the Board link or change the Board link to a drop-down list of boards the user can open.

**Comment by Kuzame** [comment]
I agree with the proposed fix, I can include this later on the codeCleanup branch. But need someone to merge the pull requests first before I move on
