### ISSUE TITLE
Set up a SQL Database

### ISSUE THREAD

**Issue by lepatrick714** [ReflexCS180/ReflexManagment#8]
Need a database to store all user's activities, instances, and profile

Acceptance Criteria:
- Construct an SQL Table contacting user's profile 
- Hash the user's personal materials 
- As a User's, I want all my saved work to be available when I come back

**Comment by lepatrick714** [comment]
@SurlySilverback Paste any websites and resources here

**Comment by lepatrick714** [comment]
tentative ER_diagram for the Reflex database.

![reflexerdiagram](https://user-images.githubusercontent.com/14812977/32177937-b4ccb6ce-bd48-11e7-8825-0846f884bce1.jpg)

**Comment by SurlySilverback** [comment]
[Reflex_ER_Diagram.pdf](https://github.com/ReflexCS180/ReflexManagment/files/1444852/Reflex_ER_Diagram.pdf)

Updated Reflex ER Diagram. Includes user-card relations.

**Comment by SurlySilverback** [comment]
**Tentative PostgreSQL Setup Procedure**
sudo su postgres
cd /tmp/postgres

/* Copy the below two lines and then paste them and execute them */
export PATH=/usr/lib/postgresql/9.5/bin:$PATH
export PGDATA=/tmp/root/test/data

pg_ctl -o "c unit_socket_directories=/run/postgresql/" -D $PGDATA -l /tmp/postgres/logfile start
createdb -h /run/postgresql/ ReflexDB
psql -h /run/postgresql/ ReflexDB

/* Make sure you're in the folder where the sql file you wish to run is located */

psql -h /run/postgresql/ ReflexDB < sql_file_name.sql

**Comment by SurlySilverback** [comment]
This is a PostgreSQL database. We need to figure out how to grab input from the user/front-end and turn those strings into SQL queries/back-end directives.

Is this the purview of Django? Find out on the next exciting episode.
